### ISSUE TITLE
error at build for backgroundColor attribute

### ISSUE THREAD

**Issue by satoyan** [AbdOoSaed/flutter_cached_pdfview#112]
**Describe the bug**
An error below ocured when I ran my app 

```
../../../.pub-cache/hosted/pub.dev/flutter_cached_pdfview-0.4.3/lib/src/pdf_view_wrapper.dart:41:7: Error: No named parameter with the name 'backgroundColor'.
      backgroundColor: pdf.backgroundColor,
      ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/flutter_pdfview-1.3.2/lib/flutter_pdfview.dart:19:9: Context: Found this candidate, but the arguments don't match.
  const PDFView({
        ^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

**To Reproduce**
Steps to reproduce the behaviour:
_```lib/feature/common/ui/widget/pdf_viewer.dart:41```_
```dart
      child: PDF(
        onError: logger.e,

      ).fromUrl(
        url,
```

**Expected behaviour**
compile done successfully.

**Comment by binSaed** [comment]
Add this to your pubspec.yaml file:

```
dependencies:
  flutter_pdfview: 1.3.4
```

**Comment by satoyan** [comment]
Because storefind depends on flutter_cached_pdfview ^1.4.3 which doesn't match any versions, version solving failed.                                                                
                                                                                                                                                                                    
                                                                                                                                                                                    
You can try the following suggestion to make the pubspec resolve:                                                                                                                   
* Consider downgrading your constraint on flutter_cached_pdfview: flutter pub add flutter_cached_pdfview:^0.4.3

**Comment by satoyan** [comment]
my pubspecl.yaml is below

```
  flutter_cached_pdfview: ^0.4.3
```
and problem is not resolved yet.
I tried run example app of this package but it did not work. @binSaed

**Comment by satoyan** [comment]
@binSaed  
thank you.

Then you need to write that somewhere in document .
