### ISSUE TITLE
Blurry text after scrolling/translating coordinates

### ISSUE THREAD

**Issue by albatrosify** [AbdOoSaed/flutter_cached_pdfview#15]
**Describe the bug**
When moving around the page, the renderer often keeps some areas blurry.

**To Reproduce**
1. Open a PDF on android.
2. Zoom in
3. Move the page around.

**Expected behavior**
Text should be rendered cleary.

**Screenshots**

![photo5373100247775031118](https://user-images.githubusercontent.com/64252708/92253739-2cc5f300-eed0-11ea-8e47-678c9a47feb6.jpg)

**Smartphone (please complete the following information):**
 - Pixel 2 XL
 - 11 (but other (previous) versions same behaviour

**Comment by AbdOoSaed** [comment]
hi @suxma 
please open your issue in repository of [pdf_view](https://github.com/endigo/flutter_pdfview)
because flutter_cached_pdfview depend on it
