### ISSUE TITLE
How  to place a scroll handle.

### ISSUE THREAD

**Issue by mahtoBabu** [AbdOoSaed/flutter_cached_pdfview#16]
I dont know if this package have scroll handle . if yes kindly help me to set it in pdf view.
If this package don't have scroll handle, kindly add.

**Comment by AbdOoSaed** [comment]
hi @suxma 
please open your issue in repository of [pdf_view](https://github.com/endigo/flutter_pdfview)
because flutter_cached_pdfview depend on it

**Comment by AbdOoSaed** [comment]
https://github.com/endigo/flutter_pdfview/issues/58
