### ISSUE TITLE
onLinkHandle Always Open Safari Browser when click link inside PDF File

### ISSUE THREAD

**Issue by suxma** [AbdOoSaed/flutter_cached_pdfview#17]
I use iPhone 11 for test my project.

I used onLinkHandle for handle value text link when click a link inside PDF File.
But always safari will open after click the link inside pdf file ( etc link is "https://pub.dev". )

Can I stop open safari browser after click link inside PDF File, and just get text link with onLinkHandle without open safari browser?

**Comment by AbdOoSaed** [comment]
hi @suxma 
please open your issue in repository of [pdf_view](https://github.com/endigo/flutter_pdfview)
because flutter_cached_pdfview depend on it

**Comment by suxma** [comment]
Hi @AbdOoSaed 

thanks. I'll issue to pdf_view repo..
