### ISSUE TITLE
I have an idea....

### ISSUE THREAD

**Issue by Romavic** [AbdOoSaed/flutter_cached_pdfview#18]
**How about adding durability to save data in the cache?**.

Like this package, you can add the time that files are stored in your cache.
Link: https://github.com/Baseflow/flutter_cache_manager/tree/develop/flutter_cache_manager

**Comment by AbdOoSaed** [comment]
thanks, it is already added
please check this link
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/6d1aa21df5e2c48e20f492b794cddae86bbc1ffd/lib/src/pdf_view_types.dart#L38
