### ISSUE TITLE
I test in 2 devices, and pdf view only show screen white. the document pdf don't show.

### ISSUE THREAD

**Issue by Romavic** [AbdOoSaed/flutter_cached_pdfview#19]
**On android System version 9,show this error.**

D/        (31775): Gralloc Register  w:720, h:1344, f:0x1, usage:0x300, ui64Stamp:280791, sSize:3870720, line = 2106
D/com.shockwave.pdfium.PdfiumCore(31775): Starting PdfiumAndroid 1.9.0
D/        (31775): Gralloc Register  w:720, h:1344, f:0x1, usage:0x300, ui64Stamp:280797, sSize:3870720, line = 2106
W/enhada.humbitec(31775): type=1400 audit(0.0:1419930): avc: denied { read } for name="u:object_r:jsonweb_default_prop:s0" dev="tmpfs" ino=12128 scontext=u:r:untrusted_app:s0:c229,c256,c512,c768 tcontext=u:object_r:jsonweb_default_prop:s0 tclass=file permissive=0
E/libc    (31775): Access denied finding property "qemu.hw.mainkeys"
E/libc    (31775): Access denied finding property "ro.vendor.hwui.texture_cache_size"
W/RenderThread(31775): type=1400 audit(0.0:1419931): avc: denied { read } for name="u:object_r:vendor_hwui_prop:s0" dev="tmpfs" ino=12177 scontext=u:r:untrusted_app:s0:c229,c256,c512,c768 tcontext=u:object_r:vendor_hwui_prop:s0 tclass=file permissive=0
D/OpenGLRenderer(31775): textureCacheSize 25165824
E/libc    (31775): Access denied finding property "ro.vendor.hwui.texture_cache_size"
D/OpenGLRenderer(31775): textureCacheSize 25165824
W/RenderThread(31775): type=1400 audit(0.0:1419932): avc: denied { read } for name="u:object_r:vendor_hwui_prop:s0" dev="tmpfs" ino=12177 scontext=u:r:untrusted_app:s0:c229,c256,c512,c768 tcontext=u:object_r:vendor_hwui_prop:s0 tclass=file permissive=0
I/OpenGLRenderer(31775): queryNativeWindowStatus 0x87844808 query=0 dataspace=0
E/enhada.humbite(31775): No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
D/        (31775): Gralloc Register  w:720, h:1344, f:0x1, usage:0xb00, ui64Stamp:280805, sSize:3870720, line = 2106
D/        (31775): Gralloc Register  w:720, h:1344, f:0x1, usage:0xb00, ui64Stamp:280811, sSize:3870720, line = 2106
D/        (31775): Gralloc Register  w:720, h:1344, f:0x1, usage:0x300, ui64Stamp:280813, sSize:3870720, line = 2106

**On android System version 8,show this error.**

D/com.shockwave.pdfium.PdfiumCore(  794): Starting PdfiumAndroid 1.9.0
D/mali_winsys(  794): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
E/zygote  (  794): No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
I/zygote  (  794): Do partial code cache collection, code=61KB, data=58KB
I/zygote  (  794): After code cache collection, code=61KB, data=58KB
I/zygote  (  794): Increasing code cache capacity to 256KB

**Comment by AbdOoSaed** [comment]
flutter clean 
update to the last version =>    flutter_cached_pdfview: ^0.2.3+4

If it still not work, please let me know

**Comment by Romavic** [comment]
@AbdOoSaed Now it's working fine...
