### ISSUE TITLE
How to show page controller

### ISSUE THREAD

**Issue by savandev17** [AbdOoSaed/flutter_cached_pdfview#2]
This is an awesome plugin for pdf viewer in a flutter, It looks clean and easy to implement, I have tried many plugins on "pub.dev", May I ask some question how can we show page total and page controller Could you please advise.

**Comment by AbdOoSaed** [comment]
![Video](https://user-images.githubusercontent.com/33700292/84597606-ec4b6180-ae19-11ea-9013-b3b5a977a87a.gif)

**Comment by AbdOoSaed** [comment]
@savandev17 
I think this what u need 
I just update the example 
please take a look

https://github.com/AbdOoSaed/flutter_cached_pdfview/tree/master/example

**Comment by savandev17** [comment]
Thank you very much sir, it's working fine now.
