### ISSUE TITLE
Issue with apk size

### ISSUE THREAD

**Issue by amanv8060** [AbdOoSaed/flutter_cached_pdfview#20]
Using this package adds up approximately 15 mb to my apk . Is there some optimization

**Comment by AbdOoSaed** [comment]
15MB is so big
I have more than an app in google play using my package and app size 9MB approx

### so I will give u some advice 
#### - size in debug mode is different from release mode 
#### - don't upload apk to google play it is recommended to use appbundle to let google split it to different CPU architecture
#### - and don't forget to add proguard-rules.pro
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/8ca667d27234cde23a8ebef0e3220ec90a98dba2/example/android/app/proguard-rules.pro#L1
#### - and build.gradle from line 49 to 69
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/8ca667d27234cde23a8ebef0e3220ec90a98dba2/example/android/app/build.gradle#L49

**Comment by amanv8060** [comment]
i have attahced size analysis for both ,this is of a specific apk architecture , not fat apk
 
[size jsons.zip](https://github.com/AbdOoSaed/flutter_cached_pdfview/files/5379528/size.jsons.zip)

**Comment by AbdOoSaed** [comment]
## the diff is only 3MB when u use bundle
![DIF](https://user-images.githubusercontent.com/33700292/96033153-9660e780-0e14-11eb-8216-69c08acd9a3d.PNG)

**Comment by amanv8060** [comment]
No its 18 mb , I am surprised too , that why adding this is causing issue 
I tried atleast 7-8 times before and after filing the issue

**Comment by AbdOoSaed** [comment]
18MB for all architectures
every device only use one architecture
google play will split ur bundle

**Comment by amanv8060** [comment]
Yes , i am aware of that , notice that , these are the analysis for specific cpu structure not of fat apk
