### ISSUE TITLE
Blank screen is displayed when change orientation

### ISSUE THREAD

**Issue by yazanIbrahim** [AbdOoSaed/flutter_cached_pdfview#24]
a blank screen is displayed when changing orientation

1. open a pdf from URL 
2. change orientation from portrait to landscape and vise versa

**Expected behaviour**
the pdf file should continue displaying 

**Smartphone (please complete the following information):**
 - Device:Honor 8x
 - OS: Android 
 - version 10

sample code 
`
class PDFViewer extends StatefulWidget {
  final String url;

  PDFViewer({@required this.url});

  @override
  _PDFViewerState createState() => _PDFViewerState();
}

class _PDFViewerState extends State<PDFViewer> {

  @override
  Widget build(BuildContext context) {
    return View(
      builder: (context, model, child) {
        return Scaffold(
          body: SafeArea(
            child: PDF(
              nightMode: true,
              onError: (error){
                print("err");
                print(error.toString());
              }
            ).cachedFromUrl(
              widget.url,
              placeholder: (progress) => Center(child: Text('$progress %')),
              errorWidget: (error) => Center(child: Text(error.toString())),
            ),
          ),
        );
      },
    );
  }
}`

**Comment by AbdOoSaed** [comment]
hi @yazanIbrahim 
please take a look at this workaround
https://github.com/endigo/flutter_pdfview/issues/9#issuecomment-532824876
