### ISSUE TITLE
Massive app size increase after install this plugin

### ISSUE THREAD

**Issue by SaliBhdr** [AbdOoSaed/flutter_cached_pdfview#25]
**Describe the bug**
Before installing the plugin, my app was 26.3 Mb and After I install the `^0.2.8` version of this plugin the app size increased up to 44.6Mb on android

**To Reproduce**
Install the plugin and run `flutter build apk --release`

**Expected behavior**
There is at least an 18Mb gap between two builds. Is the plugin has this much size?

**Desktop (please complete the following information):**
 - OS: Widows
 - Version: 10

**Smartphone (please complete the following information):**
 - Device: Nexus 5x Emulator
 - OS: Android
 - Version 9.0

**Comment by AbdOoSaed** [comment]
you can check my last app I use the package with it
https://play.google.com/store/apps/details?id=com.Suhaib_Digital_Base&hl=en_US
total app size this between 8.5MB to 11MB
_PLEASE DON'T USE APK_  **=> use appbundle**

**Comment by SaliBhdr** [comment]
@AbdOoSaed But what if I don't want to use the app bundle? 
In fat app build mode, When I build apk without the pdf reader plugin, It was about half the size when the plugin was installed. do you have any idea what could cause this? some wrong config in .gradle or something like that.

**Comment by AbdOoSaed** [comment]
@SaliBhdr 
we use [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) for view pdf in android
as he says in package doc 
_Android PdfViewer depends on PdfiumAndroid, which is set of native libraries (almost 16 MB) for many architectures._

for this In the fat app, the size will increase by 16 MB

u can read the whole doc in this [link](https://github.com/barteksc/AndroidPdfViewer#why-resulting-apk-is-so-big)

the solution => split ur apk to many architectures or use appbundle as I  said

**Comment by SaliBhdr** [comment]
@AbdOoSaed Ooow. I see!! I happened to be very surprised why this happened. Thanks for the explanation.

**Comment by AbdOoSaed** [comment]
@SaliBhdr 
have a nice day
now I will close the issue 
If you have any questions please reopen it
