### ISSUE TITLE
filePath - does it get the cached file path?

### ISSUE THREAD

**Issue by yakeer** [AbdOoSaed/flutter_cached_pdfview#26]
I'm using cacheFromURL, and I want to get the cached filePath in order to use it with "Share".

I'm missing something, can't find the filePath property.

Please help.

**Comment by AbdOoSaed** [comment]
`PDF().cachedFromUrl(
        url,
        whenDone: (String filePath) => print(filePath))`

**Comment by yakeer** [comment]
cachedFromUrl does seem to have the whenDone function...

**Comment by yakeer** [comment]
was using 0.2.9, just upgraded to 0.3.0 and it appears.
