### ISSUE TITLE
App has stopped on production

### ISSUE THREAD

**Issue by savandev17** [AbdOoSaed/flutter_cached_pdfview#3]
This is awesome plugin, It's working fine when running on the emulator but I have some issue when released app to pay store, it show the error app has stopped when pdf view try to loading, 
thought might need to add this line "-keep class com.shockwave.**" but not sure where need to add it,
could you please advise, thank you.

**Comment by AbdOoSaed** [comment]
**Hi** @savandev17 
u need to make a file named=>    proguard-rules.pro
and put on it this line            =>  -keep class com.shockwave.**
path for the file  urFlutterApp/android/app/proguard-rules.pro

and this the link for the file in the example
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/master/example/android/app/proguard-rules.pro


and also u need to add this configuration in ur 
urFlutterApp/android/app/**build.gradle**
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/master/example/android/app/build.gradle#L49

            useProguard true
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'

**Comment by savandev17** [comment]
Thank you so much for your best support sir, it's working fine now.
