### ISSUE TITLE
Please review the class DownloadIndicator.

### ISSUE THREAD

**Issue by Romavic** [AbdOoSaed/flutter_cached_pdfview#4]
In the DownloadIndicator class, if Text ('Downloading ...') appears, you should have the programmer's option to write whatever he wants in place of "Downloading".

So Text ('Downloading ...'), it should just be a Widget, which for anyone who wants to use the library should, put whatever he wants, while downloading the pdf ...

It may be the case that in place of Text ('Downloading ...'), I want to put a Gif ... or something else ...

Do you understand what I want?

**Comment by AbdOoSaed** [comment]
Hi @Romavic 

thanks, for comments that helped me
 less than 1 hour I will push new code

![Screen Recording 2020-07-30 at 3 21 32 PM](https://user-images.githubusercontent.com/33700292/88928256-e51ccd80-d278-11ea-8151-467509edd6db.gif)

**Comment by AbdOoSaed** [comment]
take a look now
https://github.com/AbdOoSaed/flutter_cached_pdfview#with-placeholder-until-pdffile-download-and-errorwidget-if-there-are-problem

**Comment by Romavic** [comment]
@AbdOoSaed It's better now ... Thanks for taking my suggestion into consideration.

**Comment by Romavic** [comment]
@AbdOoSaed...
When I test the app on the emulator, I see this error:

D/com.shockwave.pdfium.PdfiumCore( 3943): Starting PdfiumAndroid 1.9.0
E/MethodChannel#flutter/platform_views( 3943): Failed to handle method call
E/MethodChannel#flutter/platform_views( 3943): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#flutter/platform_views( 3943): 	at io.endigo.plugins.pdfviewflutter.FlutterPDFView.getBoolean(FlutterPDFView.java:171)
E/MethodChannel#flutter/platform_views( 3943): 	at io.endigo.plugins.pdfviewflutter.FlutterPDFView.<init>(FlutterPDFView.java:33)
E/MethodChannel#flutter/platform_views( 3943): 	at io.endigo.plugins.pdfviewflutter.PDFViewFactory.create(PDFViewFactory.java:22)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:179)
E/MethodChannel#flutter/platform_views( 3943): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:389)
E/MethodChannel#flutter/platform_views( 3943): 	at android.app.Dialog.show(Dialog.java:293)
E/MethodChannel#flutter/platform_views( 3943): 	at android.app.Presentation.show(Presentation.java:235)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:94)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:47)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:112)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views( 3943): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter/platform_views( 3943): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 3943): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter/platform_views( 3943): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter/platform_views( 3943): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/MethodChannel#flutter/platform_views( 3943): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 3943): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/MethodChannel#flutter/platform_views( 3943): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/flutter ( 3943): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)
E/flutter ( 3943): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 3943): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 3943): <asynchronous suspension>
E/flutter ( 3943): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 3943): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
E/flutter ( 3943): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
E/flutter ( 3943): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
E/flutter ( 3943): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
E/flutter ( 3943): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter ( 3943): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter ( 3943): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3943): #10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
E/flutter ( 3943): #11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
E/flutter ( 3943): #12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
E/flutter ( 3943): #13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
E/flutter ( 3943): #14     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
E/flutter ( 3943): #15     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
E/flutter ( 3943): #16     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
E/flutter ( 3943): #17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
E/flutter ( 3943): #18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
E/flutter ( 3943): #19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
E/flutter ( 3943): #20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
E/flutter ( 3943): #21     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
E/flutter ( 3943): #22     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 3943): #23     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 3943): #24     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 3943): #25     _invoke (dart:ui/hooks.dart:261:10)
E/flutter ( 3943): #26     _drawFrame (dart:ui/hooks.dart:219:3)
E/flutter ( 3943): 
D/        ( 3943): HostConnection::get() New Host Connection established 0x9aa91c80, tid 3955
D/        ( 3943): HostConnection::get() New Host Connection established 0x82734a80, tid 4021
D/        ( 3943): HostConnection::get() New Host Connection established 0x9aa91c00, tid 3952
