### ISSUE TITLE
Printing and sharing pdf from url

### ISSUE THREAD

**Issue by qbait** [AbdOoSaed/flutter_cached_pdfview#40]
The pdf from URL is already cached by the package, so it would be super convenient to be able to share and print that cached pdf.

**Comment by AbdOoSaed** [comment]
u can access file path like this
`PDF().cachedFromUrl( url, whenDone: (String filePath) => print(filePath))`
after get file path u can make what u want like share, print etc

**Comment by qbait** [comment]
Perfect. Thank you!
