### ISSUE TITLE
PDF not able to load in Android version 4.4

### ISSUE THREAD

**Issue by mobashshirurrahman** [AbdOoSaed/flutter_cached_pdfview#42]
hi sir
In android version 4.4 pdf is not able to load. and show 
Please fix the issue.

**Comment by AbdOoSaed** [comment]
I downloading emulator with android  4.4  to test it

**Comment by AbdOoSaed** [comment]
this an issue in flutter 
https://github.com/flutter/flutter/issues/23728

for now, I can't solve it we are supporting API 20 and up.
