### ISSUE TITLE
How to make a widget test of this component?

### ISSUE THREAD

**Issue by mdmota** [AbdOoSaed/flutter_cached_pdfview#43]
I know the component is on the screen, because I put a key on your ancestor and verified that the ancestor was found

final PDFWidget = find.byType(PDF);
expect(PDFWidget, findsOneWidget);

return _WidgetTypeFinder:<zero widgets with type "PDF" (ignoring offstage widgets)

**Comment by AbdOoSaed** [comment]
@mdmota 
u can use `find.byKey`

    final Finder PDFWidget = find.byKey(Key('pdfFromUrlKey'));
    expect(PDFWidget, findsOneWidget);

**Comment by AbdOoSaed** [comment]
`PDF().cachedFromUrl(
        'url',
        key: Key('pdfFromUrlKey'),
      )`

**Comment by mdmota** [comment]
ah ok, good alternative.
thank you
