### ISSUE TITLE
Inverted frames

### ISSUE THREAD

**Issue by AndreDrummer** [AbdOoSaed/flutter_cached_pdfview#44]
Large inverted frames appearing when loading PDF from URL.

![101652746-5f2a4380-3a1d-11eb-95c7-d53827604e81](https://user-images.githubusercontent.com/36930816/107425685-0ef35e80-6afe-11eb-92b2-0b07a46e9327.jpeg)

**Comment by AbdOoSaed** [comment]
are you use night mode?

**Comment by AbdOoSaed** [comment]
@AndreDrummer 
please look to this issue
https://github.com/endigo/flutter_pdfview/issues/123

**Comment by AndreDrummer** [comment]
I'm not using night mode. I've already updated minSdkVersion to 28 but nothing solved. 
I downloaded the package and I'm trying to fix the problem.

BUT THERE IS ONE IMPORTANT THING:

The error only happens on device Redmi Note 8 PRO. In any other device works perfectly. But even so, I need to solve it because is an enterprise app.

**Comment by AndreDrummer** [comment]
Why this was closed if is not solved?

**Comment by MonipichMP** [comment]
I met this issue too on device Xiaomi Redmi product while on other devices like Samsung worked perfectly.
