### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by peterscodee** [AbdOoSaed/flutter_cached_pdfview#47]
**Is your feature request related to a problem? Please describe.**
This is a request to add support for null safety to this package.

**Describe the solution you'd like**
**Describe alternatives you've considered**

**Additional context**
 See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.
[https://dart.dev/null-safety](https://dart.dev/null-safety)
[https://dart.dev/null-safety/faq](https://dart.dev/null-safety/faq)

**Comment by stijnie2210** [comment]
I've submitted a pullrequest #48 for this 💯

**Comment by AbdOoSaed** [comment]
flutter_cached_pdfview: ^0.4.0-nullsafety
