### ISSUE TITLE
No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String)

### ISSUE THREAD

**Issue by logblythe** [AbdOoSaed/flutter_cached_pdfview#49]
**Describe the bug**
When trying to get pdf from the network, the pdf gets loaded to 100% but only a white screen is shown instead of pdf itself.
I can see this error in the log.

**To Reproduce**
I am using the code to fetch pdf from the network from the example itself.

**Comment by Nandan-Wewhare** [comment]
The same error occurring in my project too. 
@AbdOoSaed

**Comment by Nandan-Wewhare** [comment]
@logblythe 
Try `flutter clean`. It worked for me.

**Comment by logblythe** [comment]
> @logblythe
> Try `flutter clean`. It worked for me.

Thanks @Nandan-Wewhare 
It helped me. What do think might be the root cause?

**Comment by AbdOoSaed** [comment]
thanks @Nandan-Wewhare 

@logblythe 
I think it's a general issue with Flutter
the prob is with GeneratedPluginRegistrant it's 
a generated file by Flutter build/run
sometimes flutter have a problem with caching

and "flutter clean" will fix it

![11](https://user-images.githubusercontent.com/33700292/110373440-59380480-8004-11eb-9065-ed762a62caf7.PNG)
![22](https://user-images.githubusercontent.com/33700292/110373449-5ccb8b80-8004-11eb-937f-5af88ba7a400.PNG)
