### ISSUE TITLE
Blank screen after rotate screen

### ISSUE THREAD

**Issue by itmediacreations** [AbdOoSaed/flutter_cached_pdfview#5]
Once the Pdf will download it displays correctly but after screen will rotate it displays as blank screen even after I will return to previous rotation screen. Is there some option I can provide or is it someting on my side?

**To Reproduce**
1. Download PDF
2. Once downloaded and displayed rotate phone screen

**Expected behavior**
Blank screen instead of pdf document.

**Video**
https://streamable.com/8hk3jv

**Screenshot of code**
https://prnt.sc/trly4l

**Comment by AbdOoSaed** [comment]
Hi @itmediacreations 
this is an issue in the package I depend on it 
but there are more than workaround to solve the issue

look here
https://github.com/endigo/flutter_pdfview/issues/9

**Comment by itmediacreations** [comment]
Thank you very much. I used solutions from GENL.
