### ISSUE TITLE
Old path_provider version causes import failure

### ISSUE THREAD

**Issue by wellbranding** [AbdOoSaed/flutter_cached_pdfview#51]
Please, update dependencies, because right now I can't integrate the library:
Because ess_front depends on flutter_cached_pdfview ^0.3.5 which depends on path_provider ^1.6.27, path_provider ^1.6.27 is required.
So, because ess_front depends on path_provider ^2.0.1, version solving failed.
pub get failed (1; So, because ess_front depends on path_provider ^2.0.1, version solving failed.)

I can't lower path_provider, because file_picker uses a newer version.

**Comment by AbdOoSaed** [comment]
Please try last version 

flutter_cached_pdfview: 0.4.0-nullsafety

**Comment by wellbranding** [comment]
Yes, I tried it, found myself.
The problem occurs with DIO right now:

Because dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0 and http >=0.13.0 depends on http_parser ^4.0.0, dio 3.0.10 is incompatible with http >=0.13.0.
And because flutter_cached_pdfview >=0.4.0-nullsafety depends on flutter_cache_manager ^3.0.0-nullsafety.1 which depends on http ^0.13.0, dio 3.0.10 is incompatible with flutter_cached_pdfview >=0.4.0-nullsafety.
So, because ess_front depends on both flutter_cached_pdfview ^0.4.0-nullsafety and dio 3.0.10, version solving failed.
pub get failed (1; So, because ess_front depends on both flutter_cached_pdfview ^0.4.0-nullsafety and dio 3.0.10, version solving failed.)

Can I somehow ignore this?

**Comment by wellbranding** [comment]
I updated to the latest DIO, problem solved. Thanks!

**Comment by AbdOoSaed** [comment]
I think u can fix it by 

dependency overrides

**Comment by AbdOoSaed** [comment]
If u stacked on it send to me ur pubspec.yaml

me@abdosaed.ml
