### ISSUE TITLE
update dependency

### ISSUE THREAD

**Issue by MedwinCorreo** [AbdOoSaed/flutter_cached_pdfview#53]
**Describe the bug**

![image](https://user-images.githubusercontent.com/16618565/112744970-54e58280-8fd7-11eb-8105-dadc497030fa.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. flutter run

**Comment by AbdOoSaed** [comment]
Please try last version 

flutter_cached_pdfview: 0.4.0-nullsafety

**Comment by MedwinCorreo** [comment]
thanks its working now
