### ISSUE TITLE
Unable to Open the Shared File of Google drive

### ISSUE THREAD

**Issue by sumitzartek** [AbdOoSaed/flutter_cached_pdfview#58]
**Describe the bug**
I have create your sample project clone and then after I tried to view the PDF 
This One : https://drive.google.com/file/d/1GkgKDPjtnv-WXd8k0Jc1y6su20RFnZy6/view?usp=sharing
I was unable to View. 

Is there any way to do this : So please tell me
`
PDF(
        swipeHorizontal: true,
      ).cachedFromUrl(
          'https://drive.google.com/file/d/1GkgKDPjtnv-WXd8k0Jc1y6su20RFnZy6/view?usp=sharing'),
    )
`

**Desktop (please complete the following information):**
 - Using in Android 10

**Comment by AbdOoSaed** [comment]
hi @sumitzartek 
this google drive link will not work because this not a download link 
now I making a helper method that's will help u to get a download link

**Comment by AbdOoSaed** [comment]
use this method to get a download link from the google drive link
```dart
String getDownloadLinkFromDrive(String driveLink) {
  final fileId = RegExp(r'/d\/(.+?)(?:\/|#|\?|$)$')
      .stringMatch(
          'https://drive.google.com/file/d/1GkgKDPjtnv-WXd8k0Jc1y6su20RFnZy6/view')
      .split('/')[2];
  if (fileId == null) return driveLink;
  return 'https://drive.google.com/uc?export=download&id=$fileId';
}
```

use it like this 

```dart
      PDF(
        swipeHorizontal: true,
      ).cachedFromUrl(getDownloadLinkFromDrive('https://drive.google.com/file/d/1GkgKDPjtnv-WXd8k0Jc1y6su20RFnZy6/view?usp=sharing)),

```

**Comment by AbdOoSaed** [comment]
@sumitzartek  let me know if this fixed ur issue

**Comment by zizy97** [comment]
I have the same issue. your solution save my time thanks friend. I waste lot of my time for it. Your solution is the best.thanks again

**Comment by ameenbadri7** [comment]
your solution saves me allot of time. 
I also waste a lot of my time on it. Your answer is the best.

Thank you
