### ISSUE TITLE
White screen in release APK in android 11 only

### ISSUE THREAD

**Issue by vitulgoyani** [AbdOoSaed/flutter_cached_pdfview#60]
when i run release apk it is show white screen and in debug mode is work well

**Comment by AbdOoSaed** [comment]
if release APK not working in all android version
look to this secation
https://github.com/AbdOoSaed/flutter_cached_pdfview#for-production-usage

**Comment by vitulgoyani** [comment]
Not solved, the same issue even I add this progaurd and make release build according to your link

**Comment by AbdOoSaed** [comment]
please try to run the example app and let me know
download the whole project not only dart files only

https://github.com/AbdOoSaed/flutter_cached_pdfview/tree/master/example

**Comment by RohithKilaparthi** [comment]
same issue

**Comment by AbdOoSaed** [comment]
same comment 

please try to run the example app and let me know
download the whole project not only dart files only

https://github.com/AbdOoSaed/flutter_cached_pdfview/tree/master/example

**Comment by vitulgoyani** [comment]
yes your code is working but at release mode, I can't test

**Comment by Sourabhbankar** [comment]
same issue

**Comment by vitulgoyani** [comment]
Does anyone have a solution or alternative?

**Comment by AbdOoSaed** [comment]
I test it with android 11 and it worked perfectly 
please download this [app](https://play.google.com/store/apps/details?id=com.Suhaib_Digital_Base) and try view pdf and let me know 



https://user-images.githubusercontent.com/33700292/125340588-ebee0480-e352-11eb-9559-dea47b13c69e.mp4

**Comment by vitulgoyani** [comment]
your app is working fine

**Comment by nhat108** [comment]
@vitulgoyani  try this solution, it's working: [https://github.com/arnaudelub/flutter_fullpdfview/issues/21#issuecomment-826481409](url)

**Comment by vitulgoyani** [comment]
your link is not wroking

**Comment by nhat108** [comment]
@vitulgoyani  did you add this line yet? i was faced your problem and solved
![image](https://user-images.githubusercontent.com/40523356/135451453-0923a11a-8b8b-4c60-81fc-476645471c52.png)

**Comment by saelco** [comment]
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.shockwave.**  { *; }

and in build.gradle:

buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**Comment by mb-auh** [comment]
I've got the same problem in both debug and release build. I wasn't using ProGuard in the first place but @saelco sadly your suggestions did not help fix the problem even after enabling it.
@AbdOoSaed I looked at the sample code of your app and I cannot find any significant differences regarding this behavior. @saelco @AbdOoSaed Which version of flutter are you using?

**Comment by EugenEistrachKC** [comment]
I have same issue, also not using proguard at all. Release apk does not work (white screen) but debug apk no issues.

**Comment by wladrbarbosa** [comment]
I have same issue, but in my case neither debug nor release doesn't work.

**Comment by vitulgoyani** [comment]
`buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true
            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            useProguard true
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }`

**Comment by AbdOoSaed** [comment]
Thanks @vitulgoyani 

it is the same as Example project
https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/804ee6adbabecb6602391339c5c46f4abdcb3a58/example/android/app/build.gradle#L48

https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/804ee6adbabecb6602391339c5c46f4abdcb3a58/example/android/app/proguard-rules.pro#L1

**Comment by vitulgoyani** [comment]
> Thanks @vitulgoyani
> 
> it is the same as Example project
> 
> https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/804ee6adbabecb6602391339c5c46f4abdcb3a58/example/android/app/build.gradle#L48
> 
> https://github.com/AbdOoSaed/flutter_cached_pdfview/blob/804ee6adbabecb6602391339c5c46f4abdcb3a58/example/android/app/proguard-rules.pro#L1

this is different 
-keep class com.shockwave.** { *; }
