### ISSUE TITLE
password property not working 

### ISSUE THREAD

**Issue by Abanoub-Showky** [AbdOoSaed/flutter_cached_pdfview#68]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AbdOoSaed** [comment]
Hi @Abanoub-Showky,
Thanks to your report I will test it today

**Comment by vineetpandit90** [comment]
Pls provide solution to ask password for pdf.
