### ISSUE TITLE
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by AzharZouhir** [AbdOoSaed/flutter_cached_pdfview#75]
it seems that [barteksc] pdf library doesnt exist in maven anymore

**Comment by skovalysh** [comment]
I have the same problem

**Comment by AbdOoSaed** [comment]
@AzharZouhir 
@skovalysh 
https://www.youtube.com/watch?v=QxrJHlffVwE

**Comment by blueeyestw** [comment]
> it seems that [barteksc] pdf library doesnt exist in maven anymore

The repo was removed from mavenCentral() for some reason.
For a workaround, just add jcenter() to android\build.gradle

**Comment by AzharZouhir** [comment]
@blueeyestw i did that and worked just fine
