### ISSUE TITLE
i dont understand

### ISSUE THREAD

**Issue by Apxllyxn** [abdoosaed/flutter_cached_pdfview#85]
sorry but i am new to github. i dont understand, where is the main.dart file?

**Comment by Abhishek01039** [comment]
https://github.com/abdoosaed/flutter_cached_pdfview/blob/master/example/lib/main.dart

Are you looking for this file?

**Comment by Apxllyxn** [comment]
> https://github.com/abdoosaed/flutter_cached_pdfview/blob/master/example/lib/main.dart
> 
> Are you looking for this file?

Thank you! didnt realised its in the example folder. thank you sir
