### ISSUE TITLE
How to use controller options?

### ISSUE THREAD

**Issue by farooq023** [abdoosaed/flutter_cached_pdfview#90]
I want to know how to use the controller options (getPageCount, getCurrentPage & setPage).
The above functions are those which are mentioned on in pub.dev/packages/flutter_cached_pdfview page .
For example if i want to jump to pg#5 of a pdf file, how can i use setPage function.

**Comment by abdoosaed** [comment]
U can find it in example folder 


https://github.com/abdoosaed/flutter_cached_pdfview/blob/master/example/lib/main.dart
